In [16]:
from datetime import datetime
import pandas as pd
import numpy as np

# Import .csv file

In [17]:
df=pd.read_csv('sample-data.csv')

In [18]:
df.head(5)

,time,accX,accY,accZ,gyrX,gyrY,gyrZ,magX,magY,magZ
0,1620022010,-5.509766,-2.220703,5.208984,3.417969,16.113281,-30.944824,-0.175195,0.006348,0.060303
1,1620022010,-5.533203,-2.210938,5.205078,-15.380859,22.277832,-27.893066,-0.175195,0.006348,0.060303
2,1620022010,-5.591797,-2.097656,5.251953,-28.564453,27.282715,-22.155762,-0.175195,0.006348,0.060303
3,1620022011,-5.517578,-2.107422,5.220703,-43.029785,37.841797,-6.103516,-0.175195,0.006348,0.060303
4,1620022011,-5.562500,-2.152344,5.306641,-57.617188,41.503906,12.451172,-0.175195,0.006348,0.060303

# Task 1

In [19]:
print(datetime.now())

2021-06-02 12:37:38.891663

In [20]:
df['time']=datetime.now()

In [21]:
df.head(5)

,time,accX,accY,accZ,gyrX,gyrY,gyrZ,magX,magY,magZ
0,2021-06-02 12:37:39.197938,-5.509766,-2.220703,5.208984,3.417969,16.113281,-30.944824,-0.175195,0.006348,0.060303
1,2021-06-02 12:37:39.197938,-5.533203,-2.210938,5.205078,-15.380859,22.277832,-27.893066,-0.175195,0.006348,0.060303
2,2021-06-02 12:37:39.197938,-5.591797,-2.097656,5.251953,-28.564453,27.282715,-22.155762,-0.175195,0.006348,0.060303
3,2021-06-02 12:37:39.197938,-5.517578,-2.107422,5.220703,-43.029785,37.841797,-6.103516,-0.175195,0.006348,0.060303
4,2021-06-02 12:37:39.197938,-5.562500,-2.152344,5.306641,-57.617188,41.503906,12.451172,-0.175195,0.006348,0.060303

# Task 2

In [24]:
df['labels']=np.nan

In [32]:
def put_label(label,start,end):
    df['labels'][start:end+1]=label
    print(df)

In [36]:
put_label(2,2,7)

                            time      accX      accY      accZ       gyrX  \
0     2021-06-02 12:37:39.197938 -5.509766 -2.220703  5.208984   3.417969
1     2021-06-02 12:37:39.197938 -5.533203 -2.210938  5.205078 -15.380859
2     2021-06-02 12:37:39.197938 -5.591797 -2.097656  5.251953 -28.564453
3     2021-06-02 12:37:39.197938 -5.517578 -2.107422  5.220703 -43.029785
4     2021-06-02 12:37:39.197938 -5.562500 -2.152344  5.306641 -57.617188
5     2021-06-02 12:37:39.197938 -5.582031 -2.158203  5.263672 -62.561035
6     2021-06-02 12:37:39.197938 -5.574219 -2.148438  5.269531 -77.941894
7     2021-06-02 12:37:39.197938 -5.558594 -2.216797  5.332031 -80.444336
8     2021-06-02 12:37:39.197938 -5.482422 -2.220703  5.378906 -74.218750
9     2021-06-02 12:37:39.197938 -5.458984 -2.220703  5.402344 -69.274902
10    2021-06-02 12:37:39.197938 -5.457031 -2.234375  5.373047 -55.236816
11    2021-06-02 12:37:39.197938 -5.484375 -2.232422  5.427734 -45.471191
12    2021-06-02 12:37:39.197938 -5.488281 -2.207031  5.460938 -29.052734
13    2021-06-02 12:37:39.197938 -5.416016 -2.144531  5.439453 -19.409180
14    2021-06-02 12:37:39.197938 -5.431641 -2.240234  5.478516  -2.197266
15    2021-06-02 12:37:39.197938 -5.443359 -2.220703  5.429688  14.831543
16    2021-06-02 12:37:39.197938 -5.429688 -2.189453  5.412109  26.306152
17    2021-06-02 12:37:39.197938 -5.435547 -2.207031  5.423828  33.874512
18    2021-06-02 12:37:39.197938 -5.457031 -2.263672  5.328125  43.029785
19    2021-06-02 12:37:39.197938 -5.453125 -2.154297  5.318359  46.142578
20    2021-06-02 12:37:39.197938 -5.482422 -2.228516  5.275391  43.334961
21    2021-06-02 12:37:39.197938 -5.546875 -2.146484  5.316406  37.963867
22    2021-06-02 12:37:39.197938 -5.509766 -2.111328  5.238281  25.756836
23    2021-06-02 12:37:39.197938 -5.572266 -2.103516  5.292969  22.338867
24    2021-06-02 12:37:39.197938 -5.556641 -2.138672  5.230469   6.591797
25    2021-06-02 12:37:39.197938 -5.591797 -2.173828  5.218750  -0.122070
26    2021-06-02 12:37:39.197938 -5.542969 -2.164062  5.222656 -23.803711
27    2021-06-02 12:37:39.197938 -5.527344 -2.201172  5.195312 -30.822754
28    2021-06-02 12:37:39.197938 -5.535156 -2.146484  5.179688 -48.400879
29    2021-06-02 12:37:39.197938 -5.539062 -2.134766  5.236328 -51.025391
...                          ...       ...       ...       ...        ...
10425 2021-06-02 12:37:39.197938 -6.408203 -1.744141  4.000000 -10.192871
10426 2021-06-02 12:37:39.197938 -6.361328 -1.830078  4.035156  -9.704590
10427 2021-06-02 12:37:39.197938 -6.351562 -1.810547  3.949219  -9.582520
10428 2021-06-02 12:37:39.197938 -6.337891 -1.796875  3.980469  -9.826660
10429 2021-06-02 12:37:39.197938 -6.384766 -1.763672  4.001953  -9.582520
10430 2021-06-02 12:37:39.197938 -6.400391 -1.835938  3.978516  -9.887695
10431 2021-06-02 12:37:39.197938 -6.365234 -1.826172  3.978516  -9.643555
10432 2021-06-02 12:37:39.197938 -6.347656 -1.796875  3.984375  -8.850098
10433 2021-06-02 12:37:39.197938 -6.410156 -1.804688  3.982422 -10.559082
10434 2021-06-02 12:37:39.197938 -6.388672 -1.783203  4.000000  -9.765625
10435 2021-06-02 12:37:39.197938 -6.365234 -1.822266  4.023438  -8.483887
10436 2021-06-02 12:37:39.197938 -6.349609 -1.792969  4.087891 -10.192871
10437 2021-06-02 12:37:39.197938 -6.390625 -1.771484  3.929688  -9.948730
10438 2021-06-02 12:37:39.197938 -6.335938 -1.800781  4.007812  -9.399414
10439 2021-06-02 12:37:39.197938 -6.369141 -1.777344  4.015625  -9.216309
10440 2021-06-02 12:37:39.197938 -6.400391 -1.816406  4.029297  -8.483887
10441 2021-06-02 12:37:39.197938 -6.406250 -1.794922  4.050781  -9.216309
10442 2021-06-02 12:37:39.197938 -6.402344 -1.792969  3.941406  -9.338379
10443 2021-06-02 12:37:39.197938 -6.373047 -1.812500  3.947266  -9.277344
10444 2021-06-02 12:37:39.197938 -6.402344 -1.761719  3.966797 -10.009766
10445 2021-06-02 12:37:39.197938 -6.380859 -1.810547  3.980469  -8.544922
10446 2021-06-02 12:37:39.197938 -6.404297 -1.763672  4.039062 -10.131836
10447 2021-06-02 12:37:39.197938 -6.376953 -1.816406  3.980469 -10.009766
10448 2021-06-02 12:37:39.197938 -6.451172 -1.812500  4.070312  -7.873535
10449 2021-06-02 12:37:39.197938 -6.351562 -1.804688  4.003906  -9.582520
10450 2021-06-02 12:37:39.197938 -6.326172 -1.777344  3.976562  -8.483887
10451 2021-06-02 12:37:39.197938 -6.398438 -1.783203  4.025391  -8.605957
10452 2021-06-02 12:37:39.197938 -6.392578 -1.792969  3.998047  -7.934570
10453 2021-06-02 12:37:39.197938 -6.388672 -1.783203  4.052734  -9.033203
10454 2021-06-02 12:37:39.197938 -6.404297 -1.738281  4.013672  -7.080078

            gyrY       gyrZ      magX      magY      magZ  labels
0      16.113281 -30.944824 -0.175195  0.006348  0.060303     NaN
1      22.277832 -27.893066 -0.175195  0.006348  0.060303     NaN
2      27.282715 -22.155762 -0.175195  0.006348  0.060303     2.0
3      37.841797  -6.103516 -0.175195  0.006348  0.060303     2.0
4      41.503906  12.451172 -0.175195  0.006348  0.060303     2.0
5      40.954590  28.259277 -0.175195  0.006348  0.060303     2.0
6      30.395508  39.855957 -0.175195  0.006348  0.060303     2.0
7      31.250000  42.236328 -0.175195  0.006348  0.060303     2.0
8      37.841797  44.128418 -0.175195  0.006348  0.060303     NaN
9      39.245605  43.212891 -0.175195  0.006348  0.060303     NaN
10     36.315918  32.714844 -0.175195  0.006348  0.060303     NaN
11     28.259277  26.062012 -0.175195  0.006348  0.060303     NaN
12     21.545410  17.456055 -0.175195  0.006348  0.060303     NaN
13     14.526367  15.441895 -0.175195  0.006348  0.060303     NaN
14     10.131836   9.643555 -0.175195  0.006348  0.060303     NaN
15     -1.647949  -2.990723 -0.175195  0.006348  0.060303     NaN
16     -1.708984  -7.995605 -0.175195  0.006348  0.060303     NaN
17     -0.427246 -16.601562 -0.175195  0.006348  0.060303     NaN
18     -9.155273 -24.414062 -0.175195  0.006348  0.060303     NaN
19     -7.507324 -31.066895 -0.175195  0.006348  0.060303     NaN
20     -2.685547 -31.250000 -0.175195  0.006348  0.060303     NaN
21     -1.342773 -32.592773 -0.175195  0.006348  0.060303     NaN
22     -5.859375 -28.686523 -0.175195  0.006348  0.060303     NaN
23      4.272461 -20.385742 -0.175195  0.006348  0.060303     NaN
24      5.676270 -13.671875 -0.175195  0.006348  0.060303     NaN
25     19.897461  -6.958008 -0.175195  0.006348  0.060303     NaN
26     16.357422  -0.488281 -0.175195  0.006348  0.060303     NaN
27     22.460938   1.953125 -0.175195  0.006348  0.060303     NaN
28     26.184082  10.437012 -0.175195  0.006348  0.060303     NaN
29     43.640137  12.512207 -0.175195  0.006348  0.060303     NaN
...          ...        ...       ...       ...       ...     ...
10425  14.465332   0.549316 -0.175195  0.006348  0.060303     NaN
10426  12.634277   2.258301 -0.175195  0.006348  0.060303     NaN
10427  14.465332   3.112793 -0.175195  0.006348  0.060303     NaN
10428  14.465332   0.915527 -0.175195  0.006348  0.060303     NaN
10429  13.244629   1.098633 -0.175195  0.006348  0.060303     NaN
10430  14.099121  -0.671387 -0.175195  0.006348  0.060303     NaN
10431  14.404297  -3.723145 -0.175195  0.006348  0.060303     NaN
10432  12.939453  -2.563477 -0.175195  0.006348  0.060303     NaN
10433  13.916016  -1.098633 -0.175195  0.006348  0.060303     NaN
10434  13.061523  -0.976563 -0.175195  0.006348  0.060303     NaN
10435  14.526367  -1.220703 -0.175195  0.006348  0.060303     NaN
10436  14.099121  -0.488281 -0.175195  0.006348  0.060303     NaN
10437  15.747070  -1.831055 -0.175195  0.006348  0.060303     NaN
10438  14.160156  -0.488281 -0.175195  0.006348  0.060303     NaN
10439  13.244629  -1.892090 -0.175195  0.006348  0.060303     NaN
10440  12.451172   0.671387 -0.175195  0.006348  0.060303     NaN
10441  13.427734   0.976563 -0.175195  0.006348  0.060303     NaN
10442  12.145996   1.892090 -0.175195  0.006348  0.060303     NaN
10443  13.732910   2.868652 -0.175195  0.006348  0.060303     NaN
10444  13.732910   1.831055 -0.175195  0.006348  0.060303     NaN
10445  13.000488   0.061035 -0.175195  0.006348  0.060303     NaN
10446  13.916016  -1.647949 -0.175195  0.006348  0.060303     NaN
10447  12.939453  -2.441406 -0.175195  0.006348  0.060303     NaN
10448  12.634277  -3.479004 -0.175195  0.006348  0.060303     NaN
10449  12.756348  -1.953125 -0.175195  0.006348  0.060303     NaN
10450  13.000488  -1.159668 -0.175195  0.006348  0.060303     NaN
10451  12.207031   0.793457 -0.175195  0.006348  0.060303     NaN
10452  12.756348  -0.549316 -0.175195  0.006348  0.060303     NaN
10453  14.282227   1.281738 -0.175195  0.006348  0.060303     NaN
10454  15.197754  -1.098633 -0.175195  0.006348  0.060303     NaN

[10455 rows x 11 columns]

c:\users\vaani\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy